---
title: "Using Smartphone Polling to Forecast the German Federal Election 2017^[The r scripts and the large parts of the raw data are available on our [GitHub repository](https://github.com/Corrod3/ElectionForecasting). For the remaining raw data please contact the authors, corresponding address: m.hemmerlein@mpp.hertie-school.org.]"
subtitle: \Large{Comparing the performance of digital and traditional polls}
author: \newline Moritz Hemmerlein & Alexander Sacharow
abstract: "Using online surveys to forecast election outcomes imposes severe challenges to pollsters. Non-representative samples and likely-voter bias skew gathered information and require adequate statistical adjustment. This paper compares different weighting methods to obtain a forecast from raw data, collected through smartphone polling and uses the average of leading polling institutes as a benchmark. We find that post-stratification including revealed last votes are an effective tool adjust polls while stratification purely on demographic factors cannot offset the sampling bias for polls with 1000-2000 responses."
header-includes:
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \fancyhead[LO,LE]{Smartphone polling}
    - \fancyfoot[LO,LE]{Election Forecasting Project}
    - \fancyfoot[RE,RO]{Moritz Hemmerlein \\ Alexander Sacharow}
    #- \footskip = 10pt
    - \usepackage{graphicx}
    - \usepackage{setspace}
    - \usepackage{subfig}
    - \usepackage{booktabs}
    - \usepackage{tabularx}
   # - \usepackage{hyperref}
    - \onehalfspacing
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
    number_sections: true
fontfamily: mathpazo
fontsize: 11pt
urlcolor: blue
bibliography:
    -  literature.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear Global environment
rm(list=ls())

# Setting Working directory
try(setwd("D:/Eigene Datein/Dokumente/Uni/Hertie/Materials/Election Forecasting/ElectionForecasting"), silent = TRUE)
try(setwd("C:/Users/Moritz/Desktop/ElectionForecasting"), silent = TRUE)

source("main.R")

# Collect packages/libraries we need for paper:
packages <- c("fontcm", "psych", "plotly")

# install packages if not installed before
for (p in packages) {
  if (p %in% installed.packages()[,1]) {
    require(p, character.only=T)
  }
  else {
    install.packages(p, repos="http://cran.rstudio.com", dependencies = TRUE)
    require(p, character.only=T)
  }
}
rm(p, packages)
```
\newpage

<!-- Simon's remarks on design paper:
- good motivation of the approach
- relevant literature discussed
- what's the matter with the large share of "Others" in the vote intent figure?
- impressive data collection effort, in particular for data post-processing/unbiasing procedures
- raking/poststratification section: good description, Goel/Obeng/Rothschild 2017) could have been credited a bit more transparently for the formulas used
- you might elaborate a bit more on the benefits and uniqueness of such an approach in the context of German elections and the polling landscape
-->

# Introduction 

```{r child = 'Final Paper/Introduction.Rmd'}
```

# Related Literature


```{r child = './Final Paper/Related_literature.Rmd'}
```


# Data Sources and Quality 

```{r child = './Final Paper/Data_sources_quality.Rmd'}
```

# Methodology


```{r child = './Final Paper/Methodology.Rmd'}
```


# Results

<<<<<<< HEAD
```{r child = './Final Paper/Results.Rmd'}
```
=======

```{r child = './Final Paper/Results.Rmd'}
```

>>>>>>> origin/master

# Conclusion


```{r child = './Final Paper/Conclusion.Rmd'}
```


# References


