---
title: | 
    | Smartphone Polling for the German Federal Election 2017
subtitle: "Election Forecasting Project"
author: "Moritz Hemmerlein & Alexander Sacharow"
abstract: "Using online surveys to forecast election outcomes imposes severe challenges to pollsters. Non-representative samples and likely-voter bias skew gathered information and require adequate statistical adjustment. This paper compares different weighting methods to obtain "
header-includes:
    - \usepackage{fancyhdr}
    - \pagestyle{fancy}
    - \fancyhead[LO,LE]{Smartphone polling}
    - \fancyfoot[LO,LE]{Election Forecasting Project}
    - \fancyfoot[RE,RO]{Moritz Hemmerlein \\ Alexander Sacharow}
    #- \footskip = 10pt
    - \usepackage{graphicx}
    - \usepackage{setspace}
    - \usepackage{subfig}
    - \usepackage{booktabs}
    - \usepackage{tabularx}
    - \onehalfspacing
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
    toc: true
    number_sections: true
fontfamily: mathpazo
fontsize: 11pt
urlcolor: blue
bibliography:
    -  literature.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Clear Global environment
rm(list=ls())

# Setting Working directory
try(setwd("D:/Eigene Datein/Dokumente/Uni/Hertie/Materials/Election Forecasting/ElectionForecasting"), silent = TRUE)
try(setwd("C:/Users/Moritz/Desktop/ElectionForecasting"), silent = TRUE)

source("main.R")

# Collect packages/libraries we need for paper:
packages <- c("fontcm", "psych", "plotly")

# install packages if not installed before
for (p in packages) {
  if (p %in% installed.packages()[,1]) {
    require(p, character.only=T)
  }
  else {
    install.packages(p, repos="http://cran.rstudio.com", dependencies = TRUE)
    require(p, character.only=T)
  }
}
rm(p, packages)
```
\newpage



# Introduction 

```{r child = 'Introduction.Rmd'}
```


# Related Literature

<!--
```{r child = './Final Paper/Related_literature.Rmd'}
```
-->

# Data Sources and Quality 

<!--
```{r child = './Final Paper/Data_sources_quality.Rmd'}
```
-->


# Methodology

<!--
```{r child = './Final Paper/Methodology.Rmd'}
```
-->

# Results

<!--
```{r child = './Final Paper/Results.Rmd'}
```
-->

# Conclusion

<!--
```{r child = './Final Paper/Conclusion.Rmd'}
```
-->

# References


